language: ruby
sudo: required
dist: xenial

services:
  - postgresql

rvm:
  - 2.5

cache: bundler
bundler_args: --without development production --jobs=3 --retry=3
before_install:
  - gem install bundler:2.0.2

before_script:
  - RAILS_ENV=test bundle exec rails db:create
  - bundle install

script:
  - bundle exec rails test
  - bundle exec rubocop
